apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker
spec:
  replicas: 3
  selector:
   matchLabels:
     app: hello-docker
  template:
    metadata:
      labels:
        app: hello-docker
    spec:
      containers:
      - name: hello-docker
        image: cmpe282/hello-docker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        command: ["python3", "app.py"]
      restartPolicy: Always